### ISSUE TITLE
[Feature Request] Show Weapon Firing Angles

### ISSUE THREAD

**Issue by Merith-TK** [ZachHembree/BuildVision2#2]
I am trying to build a ship with some modded weapons, that fit *nicely* behind some half armor blocks, and it would be nice to see their firing angles if possible
![image](https://user-images.githubusercontent.com/10422110/232338602-c72691f9-a677-4c74-a7f8-37e28669986c.png)
![image](https://user-images.githubusercontent.com/10422110/232338651-9470eb37-0173-479a-b2d8-393f0d7edde0.png)

**Comment by ZachHembree** [comment]
[Build Info](https://steamcommunity.com/sharedfiles/filedetails/?id=514062285) already has an overlay for that.
![20230417140107_1](https://user-images.githubusercontent.com/6527038/232571954-99ae4056-eea6-40cd-96a9-ac7e0bca33f2.jpg)

**Comment by Merith-TK** [comment]
what is the mapping for that?

**Comment by ZachHembree** [comment]
It's one of the overlays. Just walk up to a block, point a tool at it, and cycle through the different views using Ctrl and +/- until you find it. The numpad, if you have one, doesn't work with that bind so make sure you're using the +/- keys on the number row.
